//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Migrations.StoreProcedures {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Migrations.StoreProcedures.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --Only delete if it is a leaf
        ///CREATE PROCEDURE DeleteNode
        ///	@pnodeId INT--node need to move
        ///AS
        ///BEGIN
        ///	DECLARE @leftNodeId INT, @rightNodeId INT, @width INT, @count INT;
        ///    SELECT @leftNodeId = Lft, @rightNodeId = Rgt FROM dbo.Units WHERE Id = @pnodeId;
        ///	SET @width = @rightNodeId - @leftNodeId + 1;
        ///	SET @count = @width / 2;
        ///	IF(@count = 1)
        ///	BEGIN
        ///		UPDATE dbo.Units SET Lft = Lft - @width WHERE Lft &gt; @leftNodeId;
        ///		UPDATE dbo.Units SET Rgt = Rgt - @width WHERE Rgt &gt; @rightNodeId;
        ///		DELETE dbo.Uni [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE PROCEDURE UpdateBowers
        ///	@parent_id INT,
        ///	@id INT
        ///AS
        ///BEGIN
        ///	DECLARE @nodeId INT;
        ///    BEGIN
        ///		SELECT @nodeId = Rgt FROM dbo.Units WHERE Id = @parent_id;
        ///				UPDATE dbo.Units SET Rgt = Rgt + 2 WHERE Rgt &gt;= @nodeId;
        ///				UPDATE dbo.Units SET Lft = Lft + 2 WHERE Lft &gt; @nodeId;
        ///                UPDATE dbo.Units SET Lft = @nodeId, Rgt = @nodeId + 1 WHERE Id = @id;
        ///	END
        ///END
        ///
        ///.
        /// </summary>
        public static string UpdateBowers {
            get {
                return ResourceManager.GetString("UpdateBowers", resourceCulture);
            }
        }
    }
}
